// <auto-generated />
using System;
using Dizajno.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dizajno.Infrastructure.Migrations
{
    [DbContext(typeof(DizajnoDbContext))]
    [Migration("20260524001827_0010_AssetOwnerNonUnique")]
    partial class _0010_AssetOwnerNonUnique
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dizajno.Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChecksumSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("checksum_sha256");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("mime_type");

                    b.Property<Guid?>("OwnerSupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_supplier_id");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("url");

                    b.Property<Guid?>("VariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.HasKey("Id")
                        .HasName("pk_assets");

                    b.HasIndex("OwnerSupplierId")
                        .HasDatabaseName("ix_assets_owner_supplier_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_assets_product_id");

                    b.HasIndex("VariantId")
                        .HasDatabaseName("ix_assets_variant_id");

                    b.ToTable("assets", (string)null);
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Diff")
                        .HasColumnType("jsonb")
                        .HasColumnName("diff");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("Action", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_log_action_created_at");

                    b.HasIndex("ActorUserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_log_actor_user_id_created_at");

                    b.HasIndex("EntityType", "EntityId", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_audit_log_entity_type_entity_id_created_at");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("family");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_category_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("path");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Approved")
                        .HasColumnName("status");

                    b.Property<Guid?>("SuggestedBySupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("suggested_by_supplier_id");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("ParentCategoryId")
                        .HasDatabaseName("ix_categories_parent_category_id");

                    b.HasIndex("Path")
                        .HasDatabaseName("ix_categories_path");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_categories_status");

                    b.HasIndex("SuggestedBySupplierId")
                        .HasDatabaseName("ix_categories_suggested_by_supplier_id");

                    b.HasIndex("Family", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_family_slug");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.Floor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("FlooringProductVariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("flooring_product_variant_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Vertices")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("vertices");

                    b.HasKey("Id")
                        .HasName("pk_floors");

                    b.HasIndex("FlooringProductVariantId")
                        .HasDatabaseName("ix_floors_flooring_product_variant_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_floors_project_id");

                    b.ToTable("floors", (string)null);
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.Opening", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric(6,3)")
                        .HasColumnName("height");

                    b.Property<string>("MaterialOverrides")
                        .HasColumnType("jsonb")
                        .HasColumnName("material_overrides");

                    b.Property<decimal>("OffsetFromStart")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("offset_from_start");

                    b.Property<Guid?>("ProductVariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_variant_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<decimal>("SillHeight")
                        .HasColumnType("numeric(6,3)")
                        .HasColumnName("sill_height");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.Property<Guid>("WallId")
                        .HasColumnType("uuid")
                        .HasColumnName("wall_id");

                    b.Property<decimal>("Width")
                        .HasColumnType("numeric(6,3)")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_openings");

                    b.HasIndex("ProductVariantId")
                        .HasDatabaseName("ix_openings_product_variant_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_openings_project_id");

                    b.HasIndex("WallId")
                        .HasDatabaseName("ix_openings_wall_id");

                    b.ToTable("openings", (string)null);
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.PlacedItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("MaterialColors")
                        .HasColumnType("jsonb")
                        .HasColumnName("material_colors");

                    b.Property<string>("MaterialTextures")
                        .HasColumnType("jsonb")
                        .HasColumnName("material_textures");

                    b.Property<decimal>("PositionX")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("position_x");

                    b.Property<decimal>("PositionZ")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("position_z");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_variant_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<decimal>("Rotation")
                        .HasColumnType("numeric(8,5)")
                        .HasColumnName("rotation");

                    b.Property<decimal>("Scale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,3)")
                        .HasDefaultValue(1m)
                        .HasColumnName("scale");

                    b.Property<decimal>("ScaledDepth")
                        .HasColumnType("numeric(8,3)")
                        .HasColumnName("scaled_depth");

                    b.Property<decimal>("ScaledHeight")
                        .HasColumnType("numeric(8,3)")
                        .HasColumnName("scaled_height");

                    b.Property<decimal>("ScaledWidth")
                        .HasColumnType("numeric(8,3)")
                        .HasColumnName("scaled_width");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_placed_items");

                    b.HasIndex("ProductVariantId")
                        .HasDatabaseName("ix_placed_items_product_variant_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_placed_items_project_id");

                    b.ToTable("placed_items", (string)null);
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<decimal?>("CoverageRate")
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("coverage_rate");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("family");

                    b.Property<int?>("LeadTimeDays")
                        .HasColumnType("integer")
                        .HasColumnName("lead_time_days");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PreviewSvg")
                        .HasColumnType("text")
                        .HasColumnName("preview_svg");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<string>("TextureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("texture_url");

                    b.Property<string>("UnitOfSale")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("unit_of_sale");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("WasteFactor")
                        .HasColumnType("numeric(5,3)")
                        .HasColumnName("waste_factor");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_products_category_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_products_slug");

                    b.HasIndex("SupplierId", "Status")
                        .HasDatabaseName("ix_products_supplier_id_status");

                    b.HasIndex("Status", "Family", "CategoryId")
                        .HasDatabaseName("ix_products_status_family_category_id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes");

                    b.Property<decimal?>("BasePrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("base_price");

                    b.Property<string>("CollisionBoxes")
                        .HasColumnType("jsonb")
                        .HasColumnName("collision_boxes");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<decimal>("Depth")
                        .HasColumnType("numeric(8,3)")
                        .HasColumnName("depth");

                    b.Property<Guid?>("GlbAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("glb_asset_id");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric(8,3)")
                        .HasColumnName("height");

                    b.Property<string>("MaterialDefaults")
                        .HasColumnType("jsonb")
                        .HasColumnName("material_defaults");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("sku");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid?>("SvgPreviewAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("svg_preview_asset_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("Width")
                        .HasColumnType("numeric(8,3)")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_product_variants");

                    b.HasIndex("GlbAssetId")
                        .HasDatabaseName("ix_product_variants_glb_asset_id");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("ix_product_variants_sku");

                    b.HasIndex("SvgPreviewAssetId")
                        .HasDatabaseName("ix_product_variants_svg_preview_asset_id");

                    b.HasIndex("ProductId", "SortOrder")
                        .HasDatabaseName("ix_product_variants_product_id_sort_order");

                    b.ToTable("product_variants", (string)null);
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.ProductVariantTextureSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<string>("SlotName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slot_name");

                    b.Property<Guid>("SupplierTextureId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_texture_id");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.HasKey("Id")
                        .HasName("pk_product_variant_texture_slots");

                    b.HasIndex("SupplierTextureId")
                        .HasDatabaseName("ix_product_variant_texture_slots_supplier_texture_id");

                    b.HasIndex("VariantId", "SlotName")
                        .HasDatabaseName("ix_product_variant_texture_slots_variant_id_slot_name");

                    b.ToTable("product_variant_texture_slots", (string)null);
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<Guid?>("ThumbnailAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("thumbnail_asset_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("ThumbnailAssetId")
                        .HasDatabaseName("ix_projects_thumbnail_asset_id");

                    b.HasIndex("OwnerUserId", "DeletedAt", "UpdatedAt")
                        .HasDatabaseName("ix_projects_owner_user_id_deleted_at_updated_at");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.ProjectComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Anchor")
                        .HasColumnType("jsonb")
                        .HasColumnName("anchor");

                    b.Property<Guid?>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("GuestEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("guest_email");

                    b.Property<string>("GuestName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("guest_name");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_comment_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ShareId")
                        .HasColumnType("uuid")
                        .HasColumnName("share_id");

                    b.HasKey("Id")
                        .HasName("pk_project_comments");

                    b.HasIndex("ParentCommentId")
                        .HasDatabaseName("ix_project_comments_parent_comment_id");

                    b.HasIndex("ShareId")
                        .HasDatabaseName("ix_project_comments_share_id");

                    b.HasIndex("ProjectId", "CreatedAt")
                        .HasDatabaseName("ix_project_comments_project_id_created_at");

                    b.ToTable("project_comments", (string)null);
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.ProjectShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("InvitedEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("invited_email");

                    b.Property<Guid?>("InvitedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_user_id");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("mode");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("pk_project_shares");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_project_shares_token");

                    b.HasIndex("ProjectId", "RevokedAt")
                        .HasDatabaseName("ix_project_shares_project_id_revoked_at");

                    b.ToTable("project_shares", null, t =>
                        {
                            t.HasCheckConstraint("ck_project_shares_recipient", "(token IS NOT NULL)::int + (invited_email IS NOT NULL)::int + (invited_user_id IS NOT NULL)::int = 1");
                        });
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.ProjectVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("SceneSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("scene_snapshot");

                    b.HasKey("Id")
                        .HasName("pk_project_versions");

                    b.HasIndex("ProjectId", "CreatedAt")
                        .HasDatabaseName("ix_project_versions_project_id_created_at");

                    b.ToTable("project_versions", (string)null);
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("RequesterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_quotes");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_quotes_project_id");

                    b.HasIndex("RequesterUserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_quotes_requester_user_id_created_at");

                    b.ToTable("quotes", (string)null);
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.QuoteLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<bool>("IsCustomSize")
                        .HasColumnType("boolean")
                        .HasColumnName("is_custom_size");

                    b.Property<string>("MaterialOverrides")
                        .HasColumnType("jsonb")
                        .HasColumnName("material_overrides");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_variant_id");

                    b.Property<decimal>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(12,3)")
                        .HasDefaultValue(1m)
                        .HasColumnName("quantity");

                    b.Property<string>("QuantityUnit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("quantity_unit");

                    b.Property<Guid>("QuoteRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_request_id");

                    b.Property<decimal?>("ScaledDepth")
                        .HasColumnType("numeric(8,3)")
                        .HasColumnName("scaled_depth");

                    b.Property<decimal?>("ScaledHeight")
                        .HasColumnType("numeric(8,3)")
                        .HasColumnName("scaled_height");

                    b.Property<decimal?>("ScaledWidth")
                        .HasColumnType("numeric(8,3)")
                        .HasColumnName("scaled_width");

                    b.Property<decimal?>("SuggestedPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("suggested_price");

                    b.Property<string>("VariantSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("variant_snapshot");

                    b.HasKey("Id")
                        .HasName("pk_quote_lines");

                    b.HasIndex("ProductVariantId")
                        .HasDatabaseName("ix_quote_lines_product_variant_id");

                    b.HasIndex("QuoteRequestId")
                        .HasDatabaseName("ix_quote_lines_quote_request_id");

                    b.ToTable("quote_lines", (string)null);
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.QuoteRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.HasKey("Id")
                        .HasName("pk_quote_requests");

                    b.HasIndex("QuoteId", "SupplierId")
                        .IsUnique()
                        .HasDatabaseName("ix_quote_requests_quote_id_supplier_id");

                    b.HasIndex("SupplierId", "Status", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_quote_requests_supplier_id_status_created_at");

                    b.ToTable("quote_requests", (string)null);
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.QuoteResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("QuoteRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_request_id");

                    b.Property<DateTime>("RespondedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("RespondedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("responded_by_user_id");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("total_price");

                    b.HasKey("Id")
                        .HasName("pk_quote_responses");

                    b.HasIndex("QuoteRequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_quote_responses_quote_request_id");

                    b.ToTable("quote_responses", (string)null);
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.QuoteResponseAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<Guid>("ResponseId")
                        .HasColumnType("uuid")
                        .HasColumnName("response_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_quote_response_assets");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_quote_response_assets_asset_id");

                    b.HasIndex("ResponseId", "SortOrder")
                        .HasDatabaseName("ix_quote_response_assets_response_id_sort_order");

                    b.ToTable("quote_response_assets", (string)null);
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsTrusted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_trusted");

                    b.Property<Guid?>("LogoAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("logo_asset_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.Property<DateTime?>("SuspendedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspended_at");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("website_url");

                    b.HasKey("Id")
                        .HasName("pk_suppliers");

                    b.HasIndex("LogoAssetId")
                        .HasDatabaseName("ix_suppliers_logo_asset_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_suppliers_slug");

                    b.HasIndex("SuspendedAt")
                        .HasDatabaseName("ix_suppliers_suspended_at");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.SupplierInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<Guid?>("AcceptedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("accepted_by_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("InvitedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("invited_email");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_supplier_invites");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_supplier_invites_token_hash");

                    b.HasIndex("SupplierId", "AcceptedAt", "RevokedAt")
                        .HasDatabaseName("ix_supplier_invites_supplier_id_accepted_at_revoked_at");

                    b.ToTable("supplier_invites", (string)null);
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.SupplierMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_supplier_members");

                    b.HasIndex("SupplierId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_supplier_members_supplier_id_user_id");

                    b.ToTable("supplier_members", (string)null);
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.SupplierTexture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("RepeatU")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(4)
                        .HasColumnName("repeat_u");

                    b.Property<int>("RepeatV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(4)
                        .HasColumnName("repeat_v");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<Guid?>("ThumbnailAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("thumbnail_asset_id");

                    b.HasKey("Id")
                        .HasName("pk_supplier_textures");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_supplier_textures_asset_id");

                    b.HasIndex("ThumbnailAssetId")
                        .HasDatabaseName("ix_supplier_textures_thumbnail_asset_id");

                    b.HasIndex("SupplierId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_supplier_textures_supplier_id_name");

                    b.ToTable("supplier_textures", (string)null);
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.Translation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("field");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("lang");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_translations");

                    b.HasIndex("EntityType", "EntityId", "Lang")
                        .HasDatabaseName("ix_translations_entity_type_entity_id_lang");

                    b.HasIndex("EntityType", "EntityId", "Field", "Lang")
                        .IsUnique()
                        .HasDatabaseName("ix_translations_entity_type_entity_id_field_lang");

                    b.ToTable("translations", (string)null);
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.Wall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("EndX")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("end_x");

                    b.Property<decimal>("EndZ")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("end_z");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric(6,3)")
                        .HasColumnName("height");

                    b.Property<Guid?>("PaintProductVariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("paint_product_variant_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<decimal>("StartX")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("start_x");

                    b.Property<decimal>("StartZ")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("start_z");

                    b.Property<decimal>("Thickness")
                        .HasColumnType("numeric(6,3)")
                        .HasColumnName("thickness");

                    b.HasKey("Id")
                        .HasName("pk_walls");

                    b.HasIndex("PaintProductVariantId")
                        .HasDatabaseName("ix_walls_paint_product_variant_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_walls_project_id");

                    b.ToTable("walls", (string)null);
                });

            modelBuilder.Entity("Dizajno.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("locale");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Dizajno.Infrastructure.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("revoked_by_ip");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId", "RevokedAt")
                        .HasDatabaseName("ix_refresh_tokens_user_id_revoked_at");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.Asset", b =>
                {
                    b.HasOne("Dizajno.Domain.Entities.Supplier", "OwnerSupplier")
                        .WithMany("OwnedAssets")
                        .HasForeignKey("OwnerSupplierId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_assets_suppliers_owner_supplier_id");

                    b.HasOne("Dizajno.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_assets_products_product_id");

                    b.HasOne("Dizajno.Domain.Entities.ProductVariant", "Variant")
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_assets_product_variants_variant_id");

                    b.Navigation("OwnerSupplier");

                    b.Navigation("Product");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.Category", b =>
                {
                    b.HasOne("Dizajno.Domain.Entities.Category", "ParentCategory")
                        .WithMany("Children")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categories_categories_parent_category_id");

                    b.HasOne("Dizajno.Domain.Entities.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SuggestedBySupplierId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_categories_suppliers_suggested_by_supplier_id");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.Floor", b =>
                {
                    b.HasOne("Dizajno.Domain.Entities.ProductVariant", "FlooringProductVariant")
                        .WithMany()
                        .HasForeignKey("FlooringProductVariantId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_floors_product_variants_flooring_product_variant_id");

                    b.HasOne("Dizajno.Domain.Entities.Project", "Project")
                        .WithMany("Floors")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_floors_projects_project_id");

                    b.Navigation("FlooringProductVariant");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.Opening", b =>
                {
                    b.HasOne("Dizajno.Domain.Entities.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_openings_product_variants_product_variant_id");

                    b.HasOne("Dizajno.Domain.Entities.Project", "Project")
                        .WithMany("Openings")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_openings_projects_project_id");

                    b.HasOne("Dizajno.Domain.Entities.Wall", "Wall")
                        .WithMany()
                        .HasForeignKey("WallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_openings_walls_wall_id");

                    b.Navigation("ProductVariant");

                    b.Navigation("Project");

                    b.Navigation("Wall");
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.PlacedItem", b =>
                {
                    b.HasOne("Dizajno.Domain.Entities.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_placed_items_product_variants_product_variant_id");

                    b.HasOne("Dizajno.Domain.Entities.Project", "Project")
                        .WithMany("PlacedItems")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_placed_items_projects_project_id");

                    b.Navigation("ProductVariant");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.Product", b =>
                {
                    b.HasOne("Dizajno.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_categories_category_id");

                    b.HasOne("Dizajno.Domain.Entities.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_suppliers_supplier_id");

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.ProductVariant", b =>
                {
                    b.HasOne("Dizajno.Domain.Entities.Asset", "GlbAsset")
                        .WithMany()
                        .HasForeignKey("GlbAssetId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_product_variants_assets_glb_asset_id");

                    b.HasOne("Dizajno.Domain.Entities.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_variants_products_product_id");

                    b.HasOne("Dizajno.Domain.Entities.Asset", "SvgPreviewAsset")
                        .WithMany()
                        .HasForeignKey("SvgPreviewAssetId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_product_variants_assets_svg_preview_asset_id");

                    b.Navigation("GlbAsset");

                    b.Navigation("Product");

                    b.Navigation("SvgPreviewAsset");
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.ProductVariantTextureSlot", b =>
                {
                    b.HasOne("Dizajno.Domain.Entities.SupplierTexture", "SupplierTexture")
                        .WithMany()
                        .HasForeignKey("SupplierTextureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_variant_texture_slots_supplier_textures_supplier_te");

                    b.HasOne("Dizajno.Domain.Entities.ProductVariant", "Variant")
                        .WithMany("TextureSlots")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_variant_texture_slots_product_variants_variant_id");

                    b.Navigation("SupplierTexture");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.Project", b =>
                {
                    b.HasOne("Dizajno.Domain.Entities.Asset", "ThumbnailAsset")
                        .WithMany()
                        .HasForeignKey("ThumbnailAssetId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_projects_assets_thumbnail_asset_id");

                    b.Navigation("ThumbnailAsset");
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.ProjectComment", b =>
                {
                    b.HasOne("Dizajno.Domain.Entities.ProjectComment", "ParentComment")
                        .WithMany()
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_project_comments_project_comments_parent_comment_id");

                    b.HasOne("Dizajno.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_comments_projects_project_id");

                    b.HasOne("Dizajno.Domain.Entities.ProjectShare", "Share")
                        .WithMany()
                        .HasForeignKey("ShareId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_project_comments_project_shares_share_id");

                    b.Navigation("ParentComment");

                    b.Navigation("Project");

                    b.Navigation("Share");
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.ProjectShare", b =>
                {
                    b.HasOne("Dizajno.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_shares_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.ProjectVersion", b =>
                {
                    b.HasOne("Dizajno.Domain.Entities.Project", "Project")
                        .WithMany("Versions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_versions_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.Quote", b =>
                {
                    b.HasOne("Dizajno.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quotes_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.QuoteLine", b =>
                {
                    b.HasOne("Dizajno.Domain.Entities.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quote_lines_product_variants_product_variant_id");

                    b.HasOne("Dizajno.Domain.Entities.QuoteRequest", "QuoteRequest")
                        .WithMany("Lines")
                        .HasForeignKey("QuoteRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quote_lines_quote_requests_quote_request_id");

                    b.Navigation("ProductVariant");

                    b.Navigation("QuoteRequest");
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.QuoteRequest", b =>
                {
                    b.HasOne("Dizajno.Domain.Entities.Quote", "Quote")
                        .WithMany("Requests")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quote_requests_quotes_quote_id");

                    b.HasOne("Dizajno.Domain.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quote_requests_suppliers_supplier_id");

                    b.Navigation("Quote");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.QuoteResponse", b =>
                {
                    b.HasOne("Dizajno.Domain.Entities.QuoteRequest", "QuoteRequest")
                        .WithOne("Response")
                        .HasForeignKey("Dizajno.Domain.Entities.QuoteResponse", "QuoteRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quote_responses_quote_requests_quote_request_id");

                    b.Navigation("QuoteRequest");
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.QuoteResponseAsset", b =>
                {
                    b.HasOne("Dizajno.Domain.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quote_response_assets_assets_asset_id");

                    b.HasOne("Dizajno.Domain.Entities.QuoteResponse", "Response")
                        .WithMany("Attachments")
                        .HasForeignKey("ResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quote_response_assets_quote_responses_response_id");

                    b.Navigation("Asset");

                    b.Navigation("Response");
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.Supplier", b =>
                {
                    b.HasOne("Dizajno.Domain.Entities.Asset", "LogoAsset")
                        .WithMany()
                        .HasForeignKey("LogoAssetId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_suppliers_assets_logo_asset_id");

                    b.Navigation("LogoAsset");
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.SupplierInvite", b =>
                {
                    b.HasOne("Dizajno.Domain.Entities.Supplier", "Supplier")
                        .WithMany("Invites")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_supplier_invites_suppliers_supplier_id");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.SupplierMember", b =>
                {
                    b.HasOne("Dizajno.Domain.Entities.Supplier", "Supplier")
                        .WithMany("Members")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_supplier_members_suppliers_supplier_id");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.SupplierTexture", b =>
                {
                    b.HasOne("Dizajno.Domain.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_supplier_textures_assets_asset_id");

                    b.HasOne("Dizajno.Domain.Entities.Supplier", "Supplier")
                        .WithMany("Textures")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_supplier_textures_suppliers_supplier_id");

                    b.HasOne("Dizajno.Domain.Entities.Asset", "ThumbnailAsset")
                        .WithMany()
                        .HasForeignKey("ThumbnailAssetId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_supplier_textures_assets_thumbnail_asset_id");

                    b.Navigation("Asset");

                    b.Navigation("Supplier");

                    b.Navigation("ThumbnailAsset");
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.Wall", b =>
                {
                    b.HasOne("Dizajno.Domain.Entities.ProductVariant", "PaintProductVariant")
                        .WithMany()
                        .HasForeignKey("PaintProductVariantId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_walls_product_variants_paint_product_variant_id");

                    b.HasOne("Dizajno.Domain.Entities.Project", "Project")
                        .WithMany("Walls")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_walls_projects_project_id");

                    b.Navigation("PaintProductVariant");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Dizajno.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Dizajno.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("Dizajno.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Dizajno.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.Category", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.Product", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.ProductVariant", b =>
                {
                    b.Navigation("TextureSlots");
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.Project", b =>
                {
                    b.Navigation("Floors");

                    b.Navigation("Openings");

                    b.Navigation("PlacedItems");

                    b.Navigation("Versions");

                    b.Navigation("Walls");
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.Quote", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.QuoteRequest", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Response");
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.QuoteResponse", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("Dizajno.Domain.Entities.Supplier", b =>
                {
                    b.Navigation("Invites");

                    b.Navigation("Members");

                    b.Navigation("OwnedAssets");

                    b.Navigation("Products");

                    b.Navigation("Textures");
                });
#pragma warning restore 612, 618
        }
    }
}
