<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dizajno.Data\Dizajno.Data.csproj" />
    <ProjectReference Include="..\Dizajno.Domain\Dizajno.Domain.csproj" />
    <ProjectReference Include="..\Dizajno.Dto\Dizajno.Dto.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
